### ISSUE TITLE
Petite review

### ISSUE THREAD

**Issue by maveist** [babastienne/spotistory#4]
Voici une liste que j'ai pu dresser en faisant une review du code:

- Il manque une liste des dépendances (`requirements.txt`), pour faire en sorte qu'on puisse faire un `pip install -r requirements.txt` pour installer toute les dépendances.
- Il manque les string docs/commentaires sur une grande partie des fonctions.
- Quelques `print` qui trainent.
- On peu simplifier et rendre plus propre ce [bout de code](https://github.com/babastienne/spotistory/blob/master/spotistory/spotify.py#L73) comme ça:
```python
playlists = {}
for item in results["items"]:
	playlists[item["name"]] = item["id"]
return playlists
```

**Comment by babastienne** [comment]
Ajout d'un requirements.txt effectué.
Pour le reste le gros refactor de code effectué a rendu obsolète les remarques.

Merci pour votre collaboration.
